//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_Number { get; set; }
        public decimal Transaction_Amount { get; set; }
        public System.DateTime Transaction_Date { get; set; }
    }
}
